services:
  postgres:
    image: postgres:15
    container_name: stattracker-postgres
    environment:
      POSTGRES_DB: lifestats
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: tracker123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tracker -d lifestats"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - stattracker-network

  backend:
    build: ./backend
    container_name: stattracker-backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_HOST: stattracker-postgres
      DATABASE_PORT: 5432
      DATABASE_USER: tracker
      DATABASE_PASSWORD: tracker123
      DATABASE_NAME: lifestats
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - stattracker-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: stattracker-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - stattracker-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  stattracker-network:
    driver: bridge
