services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: lifestats
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: @Database0101
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tracker -d lifestats"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - stattracker-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://tracker:tracker123@postgres:5432/lifestats
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - stattracker-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - stattracker-network

volumes:
  postgres_data:

networks:
  stattracker-network:
    driver: bridge
